export * from "./schema/index";
export * from "./services/import-students";
export * from "./services/timetable";
export * from "./services/grading";
export * from "./services/ranking";
export * from "./services/promotion";
export * from "./services/license";
export * from "./services/cbt";
export * from "./services/lms";
export * from "./services/teacher-portal";
export { db } from "./client";
export type { Db } from "./client";
